# Generated by Django 5.1.1 on 2024-10-06 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Название курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото профиля')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='TextMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_name', models.CharField(max_length=255, verbose_name='Название текста')),
                ('text_file', models.TextField(max_length=10000, verbose_name='Текстовый материал к уроку')),
                ('text_description', models.TextField(max_length=1000, verbose_name='Описание к тексту')),
            ],
            options={
                'verbose_name': 'Текстовый материал к уроку',
                'verbose_name_plural': 'Текстовые материалы к уроку',
            },
        ),
        migrations.CreateModel(
            name='VideoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255, verbose_name='Название видео')),
                ('video_file', models.FileField(upload_to='', verbose_name='Видеоматериал к уроку')),
                ('video_description', models.TextField(max_length=1000, verbose_name='Описание видео')),
            ],
            options={
                'verbose_name': 'Видеоматериал',
                'verbose_name_plural': 'Видеоматериалы',
            },
        ),
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото профиля')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher', verbose_name='Преподаватель'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_lesson', models.PositiveIntegerField(verbose_name='Номер урока в курсе')),
                ('lesson_name', models.CharField(max_length=255, verbose_name='Название урока')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.course', verbose_name='Учебная группа')),
                ('text_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.textmaterial', verbose_name='Текстовый материал к уроку')),
                ('video_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.videomaterial', verbose_name='Видеоматериал к уроку')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
