# Generated by Django 5.1.1 on 2024-10-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='default@mail.ru', max_length=254, verbose_name='Почта'),
        ),
    ]
