# Generated by Django 5.1.1 on 2024-10-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers_images/', verbose_name='Фото профиля'),
        ),
    ]
