# Generated by Django 5.1.1 on 2024-10-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomaterial',
            name='video_file',
            field=models.FileField(upload_to='video_materials/', verbose_name='Видеоматериал к уроку'),
        ),
    ]
