# Generated by Django 5.1.1 on 2024-11-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_videomaterial_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=250, null=True, verbose_name='Описание курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=1, null=True, verbose_name='Длительность курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='for_who',
            field=models.CharField(choices=[('new', 'Начинающий'), ('middle', 'Средний'), ('pro', 'Продвинутый')], max_length=150, null=True, verbose_name='Для кого'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=1, null=True, verbose_name='Цена курса'),
        ),
    ]
