# Generated by Django 5.1.1 on 2024-11-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_categories_course_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
