# Generated by Django 5.1.1 on 2024-11-15 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_categories_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description_of_lesson',
            field=models.TextField(default='none', max_length=300, verbose_name='Описание урока'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.course', verbose_name='Курс'),
        ),
    ]
